version: '3'
services:
  service-postgres:
    image: postgres:latest
    container_name: service-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=chemReview
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootik
    volumes:
      - postgres:/var/lib/postgresql/data

  backend-app:
    build:
      context: ./backend
      dockerfile: ./ci/DockerFile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - service-postgres
  predictor-service:
    container_name: 'predictor_service'
    build:
      context: ./predictionService
      dockerfile: ./DockerFile
    restart: always
    ports:
      - 8000:8000
  frontend-app:
    build:
      context: ./chem-review-frontend
      dockerfile: ./config/ci/DockerFile
    restart: always
    ports:
      - 80:80
volumes:
  postgres:
